environment:
  matrix:
   - TARGET: 1.7.0-x86_64-pc-windows-msvc
   - TARGET: nightly-x86_64-pc-windows-msvc
   - TARGET: 1.7.0-i686-pc-windows-gnu
   - TARGET: nightly-i686-pc-windows-gnu
install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:TARGET}.exe"
  - rust-1.7.0-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - SET PATH=%PATH%;C:\MinGW\bin
  - rustc -V
  - cargo -V

build: false

test_script:
  - cargo test --verbose
